// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lolrujzjcsajujtdkmne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbHJ1anpqY3NhanVqdGRrbW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzAwMzgsImV4cCI6MjA1ODA0NjAzOH0.nTHO3jr0ui3_TmDSZVJSdWIj6_28hoWndnlEPaIbL1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);